	<div id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h4>STRAND HOTEL SINGAPORE</h4>
					<div class="links">	
						<ul>
							<li><a href="#">About Us</a></li>
							<li><a href="#">Deals</a></li>
							<li><a href="#">Rooms</a></li>
							<li><a href="#">Amenties</a></li>
						</ul>
						<ul>
							<li><a href="#">What's Nearby</a></li>
							<li><a href="#">Location</a></li>
						</ul>
						<ul>
							<li><a href="#">FAQs</a></li>
							<li><a href="#">Contact Us</a></li>
						</ul>
					</div>
					<div class="mailing-list">
						<h5>JOIN OUR MAILING LIST</h5>

						<div class="form-group has-feedback">
							<input type="text" name="email" placeholder="Your Email Address" />
							<i class="fa fa-envelope-o form-control-feedback"></i>
						</div>

						<h5>CONNECT WITH US</h5>
						<ul>
							<li><a class="social facebook" href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a class="social twitter" href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a class="social instagram" href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a class="social pinterest" href="#"><i class="fa fa-pinterest"></i></a></li>
							<li><a class="social googleplus" href="#"><i class="fa fa-google-plus"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="copyright-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<hr class="big"></hr>

					<p>&copy; 2015 The Strand Hotel Singapore. All Rights Reserved.</p>		

					<ul>
						<li><a href="#">TERMS & CONDITIONS</a></li>
						<li><a href="#">PRIVACY POLICY</a></li>
					</ul>
					<div class="clearfix"></div>	
				</div>
			</div>
		</div>
	</div>
</div><!-- page wrapper end -->