	<div id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
		<div class="container">
			<div class="row">
				<div class="col-md-3">
					<h2>newsletter sign up</h2>
					<hr class="small">
					<p>By signing up the Gryphon newsletter, be the first one to hear about our special offers, new arrivals, latest news and trends and other events.</p>

					<div class="search">
						<input type="text" name="search" placeholder="Enter your email address" />
						<button class="signup"><i class="fa fa-check"></i> <span>Sign up</span></button>
					</div>
				</div>
				<div class="col-md-6 col-md-offset-1">
					<div class="links-wrapper">
						<div class="store-links links">
							<h2>gryphon store</h2>
							<hr class="small">
							<ul>
								<li><a href="#">TEA</a></li>
								<li><a href="#">TEAWEAR</a></li>
								<li><a href="#">GIFTS</a></li>
								<li><a href="#">SUBSCRIPTION</a></li>
								<li><a href="#">DISCOVER TEA</a></li>
								<li><a href="#">SPEICAL ORDER</a></li>
								<li><a id="new" href="#new">New Theme</a></li>
								<li><a id="original" href="#original">Original Theme</a></li>
							</ul>
						</div>
						<div class="about-us-links links">
							<h2>about us</h2>
							<hr class="small">
							<ul>
								<li><a href="#">our philosophy</a></li>
								<li><a href="#">Gryphon Story</a></li>
								<li><a href="#">legacy</a></li>
								<li><a href="#">awards & Media</a></li>
								<li><a href="#">collection</a></li>
								<li><a href="#">gryphon blog</a></li>
								<li><a href="#">careers</a></li>
							</ul>
						</div>
						<div class="customer-service-link links">
							<h2>customer service</h2>
							<hr class="small">
							<ul>
								<li><a href="#">contact us</a></li>
								<li><a href="#">FAQ & help</a></li>
								<li><a href="#">delivery information</a></li>
								<li><a href="#">track order</a></li>
								<li><a href="#">locate store</a></li>
								<li><a href="#">terms & conditions</a></li>
								<li><a href="#">privacy policy</a></li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-2">
					<h2>FOLLOW US</h2>
					<hr class="small">
					<ul class="share-ctas">
						<li><a href="#" class="instagram"></a></li>
						<li><a href="#" class="pintrest"></a></li>
						<li><a href="#" class="twitter"></a></li>
						<li><a href="#" class="facebook"></a></li>
					</ul>
				</div>
			</div>
		</div>

	</div>
	<div id="copyright-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>&copy; 2013 GRYPHON TEA COMPANY.</p>
					<p>All material on this site is copyrighted by Gryphon Tea Company. Gryphon Tea Company® is a registered trademark. No images or copy on this site may be used without written permission by Gryphon Tea Company.</p>	
				</div>
			</div>
		</div>
	</div>
</div><!-- page wrapper end -->