	<div id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
		<div class="container">
			<div class="row">
				
			</div>
		</div>

	</div>
	<div id="copyright-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>&copy; 2015 The Strand Hotel Singapore. All Rights Reserved.</p>					
				</div>
			</div>
		</div>
	</div>
</div><!-- page wrapper end -->