<div id="page-wrapper">
	<div id="header-wrapper" class=""><!-- container-fluid -->
		<header id="main-header" class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="logo-wrapper hidden-xs hidden-sm visible-md visible-lg">
						<a href="index.html" class="site-logo"><img src="images/logo/main-logo.png" alt="logo"></a>
					</div>
					<div id="menu-wrapper">
						<nav id="nav-main">
							<ul class="main-menu hidden-xs hidden-sm">
								<li>
									<a href="about.html">ABOUT</a>	
								</li>
								<li>
									<a href="room.html">ROOM</a>
								</li>
								<li>
									<a href="amenities.html">AMENITIES</a>
								</li>
								<li>
									<a href="whatsnearby.html">WHAT'S NEARBY</a>
								</li>
								<li>
									<a href="location.html">LOCATION</a>
								</li>
								<li>
									<a href="deals.html">DEALS</a>
								</li>
								<li>
									<a href="faq.html">FAQ</a>
								</li>
								<li>
									<a href="contact.html">CONTACT</a>
								</li>
								<li>
									<a href="reservation.html">RESERVATIONS</a>
								</li>
							</ul>
							<!-- <i class="fa fa-bars icon-font mobile-menu-btn hidden-md hidden-lg"></i>
							<ul class="mobile-menu hidden-md hidden-lg">
								<li>
									<a href="about.html">ABOUT</a>	
								</li>
								<li>
									<a href="room.html">ROOM</a>
								</li>
								<li>
									<a href="amenities.html">AMENITIES</a>
								</li>
								<li>
									<a href="whatsnearby.html">WHAT'S NEARBY</a>
								</li>
								<li>
									<a href="location.html">LOCATION</a>
								</li>
								<li>
									<a href="deals.html">DEALS</a>
								</li>
								<li>
									<a href="faq.html">FAQ</a>
								</li>
								<li>
									<a href="contact.html">CONTACT</a>
								</li>
								<li>
									<a href="reservation.html">RESERVATIONS</a>
								</li>
							</ul> -->
						</nav>
					</div>					
				</div>
			</div>
		</header>
	</div>
