<div id="carousel" class="slider-wrapper carousel slide" data-ride="carousel">
	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item bg bg1 active">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5>adventurer paradise</h5>
					<h1>Venture Out</h1>
					<hr class="small"></hr>
					<p>Discover bespoke journeys and voyages of discovery provide unique insights into the history, culture, cuisine and the lifestyle of Strand destination.</p>
				</div>				
			</div>	
			<div class="item-cta">
				<img src="images/icons/post-icon.png"><a href="#">SHARE AS A POSTCARD</a>
			</div>
		</div>
		<div class="item bg bg2">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5>adventurer paradise 2</h5>
					<h1>Venture Out</h1>
					<hr class="small"></hr>
					<p>Discover bespoke journeys and voyages of discovery provide unique insights into the history, culture, cuisine and the lifestyle of Strand destination.</p>
				</div>				
			</div>	
		</div>
	</div>

	<!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel" data-slide-to="1"></li>
	  </ol>
</div>