<div id="carousel" class="slider-wrapper carousel slide" data-ride="carousel">

	<!-- Wrapper for slides -->
	<div class="carousel-inner">
		<div class="item bg bg1 active">
			<!-- <div class="fill" style="background-image:url('../images/content/slider-1.jpg');"> -->
				<!-- <img src="images/content/slider-1.jpg" alt="slider"> -->
				<!-- <div class="container" style="">
					<div class="row">
						<div class="col-md-12">
							
						</div>
					</div>
				</div>	 -->
				<div class="carousel-caption">
					<div class="caption-text">
						<h1>Welcome</h1>
						<h3>Get 10% off discount from your first purchase until <br>
							17th of Jan with Promo Code: SHOPNOW</h3>
						<a href="#" class="visit cta">Visit Tea Store</a>
					</div>
				</div>	
			<!-- </div> -->
		</div>
	</div>

	<a href="#content-wrapper" class="scroll-to-content"><div class="arrow bounce"></div></a>
</div>
