<div id="carousel" class="slider-wrapper carousel slide" data-ride="carousel">
	<!-- Wrapper for slides -->
	<div class="carousel-inner">
		<div class="item bg bg1 active">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5>adventurer paradise</h5>
					<h1>Venture Out</h1>
					<p>Discover bespoke journeys and voyages of discovery provide unique insights into the history, culture, cuisine and the lifestyle of Strand destination.</p>
				</div>
			</div>	
		</div>
	</div>
</div>